(function(){'use strict';
const courses=['','Парикмахер с нуля','Женские стрижки','Колористика','Блонд без ошибок','Современные окрашивания','Продвинутый мастер','Колорист-эксперт'];
const configured=window.JULI_SUPABASE_URL&&window.JULI_SUPABASE_ANON_KEY&&window.supabase;
const db=configured?window.supabase.createClient(window.JULI_SUPABASE_URL,window.JULI_SUPABASE_ANON_KEY):null;
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let meId=null,migrationNeeded=false;
const S={profiles:[],access:[],progress:[],teacherCourses:[],teacherStudents:[],finance:[],groups:[],groupMembers:[]};
const activeStudents=()=>S.profiles.filter(x=>x.role==='student'&&!x.archived);
const activeTeachers=()=>S.profiles.filter(x=>x.role==='teacher'&&!x.archived);
const byId=id=>S.profiles.find(x=>x.id===id);
const progressCount=(student,level)=>S.progress.filter(x=>x.student_id===student&&Number(x.course_level)===Number(level)&&x.completed).length;
const hasAccess=(student,level)=>!!S.access.find(x=>x.student_id===student&&Number(x.course_level)===Number(level)&&x.access_granted);
const teacherCourseSet=id=>new Set(S.teacherCourses.filter(x=>x.teacher_id===id).map(x=>Number(x.course_level)));
const teacherStudentSet=id=>new Set(S.teacherStudents.filter(x=>x.teacher_id===id).map(x=>x.student_id));
const fmtMoney=n=>Number(n||0).toLocaleString('ru-RU',{maximumFractionDigits:0})+' ₸';
function setStatus(text,type=''){const e=$('status');e.className='status '+type;e.textContent=text}
function switchTab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.section').forEach(x=>x.hidden=x.id!=='section-'+name);if(name==='overview')renderOverview();if(name==='students')renderStudents();if(name==='teachers')renderTeachers();if(name==='finance')renderFinance();if(name==='groups')renderGroups()}
async function safeSelect(table,columns='*'){const r=await db.from(table).select(columns);if(r.error){console.warn(table,r.error);migrationNeeded=true;return []}return r.data||[]}
async function loadAll(){const profilesR=await db.from('profiles').select('*').order('created_at',{ascending:false});if(profilesR.error)throw profilesR.error;S.profiles=profilesR.data||[];const accessR=await db.from('course_access').select('*');if(accessR.error)throw accessR.error;S.access=accessR.data||[];const progressR=await db.from('student_progress').select('*');S.progress=progressR.error?[]:(progressR.data||[]);if(progressR.error)migrationNeeded=true;[S.teacherCourses,S.teacherStudents,S.finance,S.groups,S.groupMembers]=await Promise.all([safeSelect('teacher_course_assignments'),safeSelect('teacher_student_assignments'),safeSelect('course_finance'),safeSelect('student_groups'),safeSelect('student_group_members')]);$('migration').hidden=!migrationNeeded;renderOverview()}
function renderOverview(){const students=activeStudents(),teachers=activeTeachers(),open=S.access.filter(a=>a.access_granted&&students.some(s=>s.id===a.student_id));const revenue=S.finance.filter(x=>x.paid).reduce((n,x)=>n+Number(x.payment_amount||0),0);const done=open.reduce((n,a)=>n+progressCount(a.student_id,a.course_level),0),avg=open.length?Math.round(done/(open.length*6)*100):0;const reward=S.finance.reduce((n,f)=>n+(f.paid&&progressCount(f.student_id,f.course_level)===6?Number(f.payment_amount||0)*Number(f.teacher_reward_percent||0)/100:0),0);$('kpis').innerHTML=[['Учеников',students.length],['Учителей',teachers.filter(x=>x.is_active).length],['Открытых ступеней',open.length],['Средний прогресс',avg+'%'],['Оплачено',fmtMoney(revenue)],['К начислению учителям',fmtMoney(reward)]].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');const loads=teachers.map(t=>({t,students:teacherStudentSet(t.id).size,courses:teacherCourseSet(t.id).size})).sort((a,b)=>b.students-a.students);$('teacherLoad').innerHTML=loads.length?loads.map(x=>`<div class="overview-item"><span>${esc(x.t.full_name||x.t.email)}</span><span>${x.students} учен. · ${x.courses} ступ.</span></div>`).join(''):'<div class="muted">Учителя ещё не назначены.</div>';const groupRows=S.groups.filter(g=>g.active!==false).map(g=>{const ids=S.groupMembers.filter(m=>m.group_id===g.id).map(m=>m.student_id);return `<div class="overview-item"><span>${esc(g.name)}</span><span>${ids.length} учен.</span></div>`});$('groupOverview').innerHTML=groupRows.length?groupRows.join(''):'<div class="muted">Группы набора ещё не созданы.</div>'}
function renderStudents(){const q=($('studentSearch').value||'').trim().toLowerCase();const list=activeStudents().filter(s=>!q||(s.full_name||'').toLowerCase().includes(q)||(s.email||'').toLowerCase().includes(q));$('students').innerHTML=list.length?list.map(studentCard).join(''):'<div class="empty">Ученики не найдены.</div>'}
function studentCard(s){const teacherNames=S.teacherStudents.filter(x=>x.student_id===s.id).map(x=>byId(x.teacher_id)).filter(Boolean).map(x=>x.full_name||x.email);return `<article class="card"><div class="card-head"><div><div class="name">${esc(s.full_name||'Без имени')}</div><div class="email">${esc(s.email)}</div></div><div class="badges"><span class="badge ${s.is_active?'ok':''}">${s.is_active?'Активен':'Заблокирован'}</span>${teacherNames.map(n=>`<span class="badge gold">${esc(n)}</span>`).join('')}</div></div><div class="card-body">${[1,2,3,4,5,6,7].map(level=>{const done=progressCount(s.id,level),pct=Math.round(done/6*100);return `<div class="course-row"><div class="course-title"><small>СТУПЕНЬ ${level}</small><strong>${courses[level]}</strong></div><label class="check"><input id="sa-${s.id}-${level}" type="checkbox" ${hasAccess(s.id,level)?'checked':''}> Доступ</label><div class="progress-mini"><div class="row"><span>${done}/6</span><strong>${pct}%</strong></div><div class="track"><div class="fill" style="width:${pct}%"></div></div></div><a class="btn" href="teacher-progress.html?student=${encodeURIComponent(s.id)}">Модули</a></div>`}).join('')}</div><div class="card-actions"><div><button onclick="window.JULI_ADMIN.toggleBlock('${s.id}',${!!s.is_active})">${s.is_active?'Заблокировать':'Разблокировать'}</button> <button class="danger" onclick="window.JULI_ADMIN.removeUser('${s.id}')">Удалить</button></div><button class="primary" onclick="window.JULI_ADMIN.saveStudentAccess('${s.id}')">Сохранить доступы</button></div></article>`}
async function saveStudentAccess(id){setStatus('Сохраняем доступы...');const rows=[1,2,3,4,5,6,7].map(level=>{const old=S.access.find(x=>x.student_id===id&&Number(x.course_level)===level)||{};return {student_id:id,course_level:level,access_granted:!!$(`sa-${id}-${level}`)?.checked,paid:!!old.paid,paid_at:old.paid_at||null,payment_note:old.payment_note||null}});const r=await db.from('course_access').upsert(rows,{onConflict:'student_id,course_level'});if(r.error){setStatus('Ошибка сохранения доступов.','err');return}setStatus('✓ Доступы сохранены.','ok');await loadAll();renderStudents()}
async function toggleBlock(id,isActive){const r=await db.from('profiles').update({is_active:!isActive,blocked_at:isActive?new Date().toISOString():null}).eq('id',id);if(r.error){setStatus('Не удалось изменить статус.','err');return}await loadAll();renderStudents()}
async function removeUser(id){if(!confirm('Удалить пользователя из системы сайта? Доступы будут закрыты, пользователь исчезнет из списков.'))return;const now=new Date().toISOString();const p=await db.from('profiles').update({archived:true,is_active:false,blocked_at:now}).eq('id',id);if(p.error){setStatus('Не удалось удалить пользователя.','err');return}await db.from('course_access').update({access_granted:false}).eq('student_id',id);setStatus('Пользователь удалён из системы сайта.','ok');await loadAll();renderStudents()}
function renderTeachers(){const candidates=activeStudents().filter(s=>s.is_active);$('teacherCandidate').innerHTML='<option value="">Выберите пользователя</option>'+candidates.map(s=>`<option value="${s.id}">${esc(s.full_name||s.email)} — ${esc(s.email)}</option>`).join('');const teachers=activeTeachers();$('teachers').innerHTML=teachers.length?teachers.map(teacherCard).join(''):'<div class="empty">Учителей пока нет. Назначьте роль одному из зарегистрированных пользователей.</div>'}
function teacherCard(t){const cs=teacherCourseSet(t.id),ss=teacherStudentSet(t.id),students=activeStudents().filter(s=>s.is_active);return `<article class="card"><div class="card-head"><div><div class="name">${esc(t.full_name||'Учитель')}</div><div class="email">${esc(t.email)}</div></div><div class="badges"><span class="badge gold">${cs.size} ступ.</span><span class="badge ok">${ss.size} учен.</span></div></div><div class="card-body"><div class="teacher-block"><div class="subhead"><h3>Доступные ступени</h3><span class="muted">Только по ним учитель сможет вести обучение</span></div><div class="checks">${[1,2,3,4,5,6,7].map(l=>`<label class="choice"><input id="tc-${t.id}-${l}" type="checkbox" ${cs.has(l)?'checked':''}> ${l}. ${courses[l]}</label>`).join('')}</div></div><div class="teacher-block"><div class="subhead"><h3>Назначенные ученики</h3><span class="muted">Учитель увидит только отмеченных</span></div><div class="checks">${students.map(s=>`<label class="choice"><input id="ts-${t.id}-${s.id}" type="checkbox" ${ss.has(s.id)?'checked':''}> ${esc(s.full_name||s.email)}</label>`).join('')||'<span class="muted">Нет учеников</span>'}</div></div></div><div class="card-actions"><button class="danger" onclick="window.JULI_ADMIN.demoteTeacher('${t.id}')">Сделать учеником</button><button class="primary" onclick="window.JULI_ADMIN.saveTeacher('${t.id}')">Сохранить назначения</button></div></article>`}
async function promoteTeacher(){const id=$('teacherCandidate').value;if(!id)return;const r=await db.from('profiles').update({role:'teacher'}).eq('id',id);if(r.error){setStatus('Не удалось назначить роль учителя. Примените актуальную схему Supabase.','err');return}setStatus('✓ Пользователь назначен учителем.','ok');await loadAll();renderTeachers()}
async function demoteTeacher(id){if(!confirm('Вернуть этому пользователю роль ученика? Все назначения учителя будут сняты.'))return;await db.from('teacher_course_assignments').delete().eq('teacher_id',id);await db.from('teacher_student_assignments').delete().eq('teacher_id',id);const r=await db.from('profiles').update({role:'student'}).eq('id',id);if(r.error){setStatus('Не удалось изменить роль.','err');return}await loadAll();renderTeachers()}
async function saveTeacher(id){setStatus('Сохраняем назначения учителя...');const levels=[1,2,3,4,5,6,7].filter(l=>$(`tc-${id}-${l}`)?.checked),students=activeStudents().filter(s=>s.is_active&&$(`ts-${id}-${s.id}`)?.checked).map(s=>s.id);let r=await db.from('teacher_course_assignments').delete().eq('teacher_id',id);if(r.error){setStatus('Ошибка сохранения ступеней.','err');return}if(levels.length){r=await db.from('teacher_course_assignments').insert(levels.map(l=>({teacher_id:id,course_level:l,assigned_by:meId})));if(r.error){setStatus('Ошибка сохранения ступеней.','err');return}}r=await db.from('teacher_student_assignments').delete().eq('teacher_id',id);if(r.error){setStatus('Ошибка сохранения учеников.','err');return}if(students.length){r=await db.from('teacher_student_assignments').insert(students.map(s=>({teacher_id:id,student_id:s,assigned_by:meId})));if(r.error){setStatus('Ошибка сохранения учеников.','err');return}}setStatus('✓ Назначения учителя сохранены.','ok');await loadAll();renderTeachers()}
function eligibleTeachers(student,level){return activeTeachers().filter(t=>teacherCourseSet(t.id).has(Number(level))&&teacherStudentSet(t.id).has(student))}
function renderFinance(){const students=activeStudents(),keys=new Set();S.access.filter(a=>a.access_granted&&students.some(s=>s.id===a.student_id)).forEach(a=>keys.add(a.student_id+'|'+a.course_level));S.finance.filter(f=>students.some(s=>s.id===f.student_id)).forEach(f=>keys.add(f.student_id+'|'+f.course_level));const rows=[...keys].map(k=>{const [student,level]=k.split('|');return financeRow(student,Number(level))});$('finance').innerHTML=rows.length?rows.join(''):'<div class="empty">Нет открытых ступеней для финансового учёта.</div>';const revenue=S.finance.filter(x=>x.paid).reduce((n,x)=>n+Number(x.payment_amount||0),0),due=S.finance.reduce((n,x)=>n+(x.paid&&progressCount(x.student_id,x.course_level)===6?Number(x.payment_amount||0)*Number(x.teacher_reward_percent||0)/100:0),0);$('financeSummary').textContent=`Получено: ${fmtMoney(revenue)} · Вознаграждение после завершения ступеней: ${fmtMoney(due)}`}
function financeRow(studentId,level){const s=byId(studentId),f=S.finance.find(x=>x.student_id===studentId&&Number(x.course_level)===level)||{},eligible=eligibleTeachers(studentId,level),done=progressCount(studentId,level),amount=Number(f.payment_amount||0),pct=Number(f.teacher_reward_percent||0),reward=amount*pct/100,ready=done===6;const teacherOptions='<option value="">Не назначен</option>'+eligible.map(t=>`<option value="${t.id}" ${f.teacher_id===t.id?'selected':''}>${esc(t.full_name||t.email)}</option>`).join('');return `<div class="finance-row"><div class="course-title"><small>${esc(s?.full_name||s?.email||'Ученик')} · СТУПЕНЬ ${level}</small><strong>${courses[level]}</strong></div><label class="label">Учитель<select class="select" id="ft-${studentId}-${level}">${teacherOptions}</select></label><label class="check"><input id="fp-${studentId}-${level}" type="checkbox" ${f.paid?'checked':''}> Оплачено</label><label class="label">Сумма<input class="field" id="fa-${studentId}-${level}" type="number" min="0" step="1000" value="${amount}"></label><label class="label">Вознаграждение %<input class="field" id="fr-${studentId}-${level}" type="number" min="0" max="100" step="0.5" value="${pct}"></label><div class="money-state">Прогресс: <strong>${done}/6</strong><br>${ready?`К начислению: <span class="money">${fmtMoney(reward)}</span>`:'Вознаграждение активируется после 6/6'}</div><button class="primary" onclick="window.JULI_ADMIN.saveFinance('${studentId}',${level})">Сохранить</button></div>`}
async function saveFinance(student,level){const paid=!!$(`fp-${student}-${level}`)?.checked,amount=Number($(`fa-${student}-${level}`)?.value||0),pct=Number($(`fr-${student}-${level}`)?.value||0),teacher=$(`ft-${student}-${level}`)?.value||null,old=S.finance.find(x=>x.student_id===student&&Number(x.course_level)===level)||{};const payload={student_id:student,course_level:level,teacher_id:teacher,paid,payment_amount:amount,paid_at:paid?(old.paid_at||new Date().toISOString()):null,teacher_reward_percent:pct,note:old.note||null};const r=await db.from('course_finance').upsert(payload,{onConflict:'student_id,course_level'});if(r.error){setStatus('Не удалось сохранить финансовые данные.','err');return}await db.from('course_access').update({paid,paid_at:payload.paid_at,payment_note:`Сумма: ${fmtMoney(amount)}; вознаграждение учителя: ${pct}%`}).eq('student_id',student).eq('course_level',level);setStatus('✓ Финансовые данные сохранены.','ok');await loadAll();renderFinance()}
function renderGroups(){const students=activeStudents();$('groups').innerHTML=S.groups.length?S.groups.map(g=>groupCard(g,students)).join(''):'<div class="empty">Группы набора ещё не созданы.</div>'}
function groupCard(g,students){const ids=new Set(S.groupMembers.filter(x=>x.group_id===g.id).map(x=>x.student_id)),members=students.filter(s=>ids.has(s.id)),revenue=S.finance.filter(f=>ids.has(f.student_id)&&f.paid).reduce((n,x)=>n+Number(x.payment_amount||0),0),access=S.access.filter(a=>ids.has(a.student_id)&&a.access_granted),done=access.reduce((n,a)=>n+progressCount(a.student_id,a.course_level),0),avg=access.length?Math.round(done/(access.length*6)*100):0;return `<article class="card"><div class="card-head"><div><div class="name">${esc(g.name)}</div><div class="email">Набор: ${g.start_date?new Date(g.start_date+'T00:00:00').toLocaleDateString('ru-RU'):'дата не указана'} · ${esc(g.description||'')}</div></div><div class="badges"><span class="badge ok">${members.length} учен.</span><span class="badge gold">${avg}% прогресс</span><span class="badge">${fmtMoney(revenue)}</span></div></div><div class="card-body"><div class="checks">${students.map(s=>`<label class="choice"><input id="gm-${g.id}-${s.id}" type="checkbox" ${ids.has(s.id)?'checked':''}> ${esc(s.full_name||s.email)}</label>`).join('')}</div></div><div class="card-actions"><button class="danger" onclick="window.JULI_ADMIN.deleteGroup(${g.id})">Удалить группу</button><button class="primary" onclick="window.JULI_ADMIN.saveGroup(${g.id})">Сохранить состав</button></div></article>`}
async function createGroup(){const name=$('groupName').value.trim();if(!name)return;const r=await db.from('student_groups').insert({name,start_date:$('groupDate').value||null,description:$('groupDesc').value.trim()||null,created_by:meId});if(r.error){setStatus('Не удалось создать группу.','err');return}$('groupName').value='';$('groupDate').value='';$('groupDesc').value='';setStatus('✓ Группа создана.','ok');await loadAll();renderGroups()}
async function saveGroup(id){const students=activeStudents().filter(s=>$(`gm-${id}-${s.id}`)?.checked).map(s=>s.id);let r=await db.from('student_group_members').delete().eq('group_id',id);if(r.error){setStatus('Не удалось сохранить состав группы.','err');return}if(students.length){r=await db.from('student_group_members').insert(students.map(s=>({group_id:id,student_id:s})));if(r.error){setStatus('Не удалось сохранить состав группы.','err');return}}setStatus('✓ Состав группы сохранён.','ok');await loadAll();renderGroups()}
async function deleteGroup(id){if(!confirm('Удалить группу набора? Ученики удалены не будут.'))return;const r=await db.from('student_groups').delete().eq('id',id);if(r.error){setStatus('Не удалось удалить группу.','err');return}await loadAll();renderGroups()}
async function init(){if(!db){location.href='login.html';return}const u=await db.auth.getUser();if(!u.data.user){location.href='login.html';return}meId=u.data.user.id;const me=await db.from('profiles').select('role,is_active,archived').eq('id',meId).single();if(me.error||!me.data){location.href='login.html';return}if(!['superteacher','owner'].includes(me.data.role)){location.href=me.data.role==='teacher'?'teacher.html':'student.html';return}try{await loadAll();setStatus(migrationNeeded?'Часть новой структуры ещё не применена. Выполните актуальный supabase-schema.sql.':'Панель готова.');switchTab('overview')}catch(e){console.error(e);setStatus('Не удалось загрузить панель. Проверьте Supabase и актуальную схему.','err')}}
document.addEventListener('click',e=>{const t=e.target.closest('.tab');if(t)switchTab(t.dataset.tab)});$('studentSearch').addEventListener('input',renderStudents);$('promoteTeacher').addEventListener('click',promoteTeacher);$('createGroup').addEventListener('click',createGroup);$('out').addEventListener('click',async()=>{await db.auth.signOut();location.href='./'});window.JULI_ADMIN={saveStudentAccess,toggleBlock,removeUser,saveTeacher,demoteTeacher,saveFinance,saveGroup,deleteGroup};init();
})();