(function(){'use strict';
const C=['','Парикмахер с нуля','Женские стрижки','Колористика','Блонд без ошибок','Современные окрашивания','Продвинутый мастер','Колорист-эксперт'];
const db=(window.supabase&&window.JULI_SUPABASE_URL&&window.JULI_SUPABASE_ANON_KEY)?window.supabase.createClient(window.JULI_SUPABASE_URL,window.JULI_SUPABASE_ANON_KEY):null;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const S={profiles:[],access:[],progress:[],tc:[],ts:[],groups:[],gm:[]};let me=null,selected=new Set(),studentEditing=null,teacherEditing=null,groupEditing=null;
const people=role=>S.profiles.filter(x=>x.role===role&&!x.archived);const students=()=>people('student');const teachers=()=>people('teacher');const candidates=()=>people('candidate');const byId=id=>S.profiles.find(x=>x.id===id);
const access=(id,l)=>S.access.find(x=>x.student_id===id&&Number(x.course_level)===l);const done=(id,l)=>S.progress.filter(x=>x.student_id===id&&Number(x.course_level)===l&&x.completed).length;
const teacherStudents=id=>new Set(S.ts.filter(x=>x.teacher_id===id).map(x=>x.student_id));const teacherCourses=id=>new Set(S.tc.filter(x=>x.teacher_id===id).map(x=>Number(x.course_level)));
const studentTeachers=id=>S.ts.filter(x=>x.student_id===id).map(x=>byId(x.teacher_id)).filter(Boolean);const studentGroups=id=>S.gm.filter(x=>x.student_id===id).map(x=>S.groups.find(g=>g.id===x.group_id)).filter(Boolean);
function st(text,type=''){const e=$('status');e.className='status '+type;e.textContent=text}
async function select(table){const r=await db.from(table).select('*');if(r.error)throw r.error;return r.data||[]}
async function load(){const p=await db.from('profiles').select('*').order('created_at',{ascending:false});if(p.error)throw p.error;S.profiles=p.data||[];[S.access,S.progress,S.tc,S.ts,S.groups,S.gm]=await Promise.all(['course_access','student_progress','teacher_course_assignments','teacher_student_assignments','student_groups','student_group_members'].map(select));renderAll()}
function renderAll(){renderSummary();renderCandidates();fillFilters();renderStudents();renderTeachers();renderGroups()}
function tab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.section').forEach(x=>x.hidden=x.id!=='section-'+name)}
function renderSummary(){const ss=students().filter(x=>x.is_active),tt=teachers().filter(x=>x.is_active),opened=S.access.filter(x=>x.access_granted&&ss.some(s=>s.id===x.student_id));$('summary').innerHTML=[['Претенденты',candidates().length],['Ученики',ss.length],['Учителя',tt.length],['Открыто ступеней',opened.length]].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}
function renderCandidates(){const q=($('candidateSearch').value||'').toLowerCase().trim();const list=candidates().filter(x=>!q||(x.full_name||'').toLowerCase().includes(q)||(x.email||'').toLowerCase().includes(q));$('candidates').innerHTML=list.length?`<div class="data-list">${list.map(x=>`<div class="data-row"><div><strong>${esc(x.full_name||'Без имени')}</strong><span>${esc(x.email)}</span></div><span class="badge gold">Претендент</span><span>${new Date(x.created_at).toLocaleDateString('ru-RU')}</span><div class="row-actions"><button class="primary" onclick="JULI.makeStudent('${x.id}')">Перевести в ученики</button></div></div>`).join('')}</div>`:'<div class="empty">Новых претендентов нет.</div>'}
async function makeStudent(id){const r=await db.from('profiles').update({role:'student'}).eq('id',id);if(r.error){st('Не удалось перевести пользователя в Ученики: '+r.error.message,'err');return}st('✓ Пользователь переведён в Ученики.','ok');await load();tab('students')}
function fillFilters(){const tVal=$('studentTeacherFilter').value,gVal=$('studentGroupFilter').value,bt=$('bulkTeacher').value,bg=$('bulkGroup').value;const tOpts=teachers().map(t=>`<option value="${t.id}">${esc(t.full_name||t.email)}</option>`).join(''),gOpts=S.groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('');$('studentTeacherFilter').innerHTML='<option value="">Все учителя</option>'+tOpts;$('studentGroupFilter').innerHTML='<option value="">Все группы</option>'+gOpts;$('bulkTeacher').innerHTML='<option value="">Назначить учителю…</option>'+tOpts;$('bulkGroup').innerHTML='<option value="">Добавить в группу…</option>'+gOpts;$('studentTeacherFilter').value=tVal;$('studentGroupFilter').value=gVal;$('bulkTeacher').value=bt;$('bulkGroup').value=bg}
function filteredStudents(){const q=($('studentSearch').value||'').toLowerCase().trim(),tf=$('studentTeacherFilter').value,gf=Number($('studentGroupFilter').value||0);return students().filter(s=>{if(q&&!((s.full_name||'').toLowerCase().includes(q)||(s.email||'').toLowerCase().includes(q)))return false;if(tf&&!S.ts.some(x=>x.teacher_id===tf&&x.student_id===s.id))return false;if(gf&&!S.gm.some(x=>Number(x.group_id)===gf&&x.student_id===s.id))return false;return true})}
function renderStudents(){const list=filteredStudents();$('studentCount').textContent=`Показано ${list.length} из ${students().length}`;$('students').innerHTML=list.length?`<div class="student-table"><div class="student-th"><span></span><span>Ученик</span><span>Учителя</span><span>Группы</span><span>Ступени</span><span></span></div>${list.map(s=>{const ts=studentTeachers(s.id),gs=studentGroups(s.id),ls=S.access.filter(x=>x.student_id===s.id&&x.access_granted).map(x=>Number(x.course_level));return `<div class="student-tr"><input type="checkbox" class="sel-student" data-id="${s.id}" ${selected.has(s.id)?'checked':''}><div><strong>${esc(s.full_name||'Без имени')}</strong><span>${esc(s.email)}</span></div><div class="mini-tags">${ts.map(x=>`<i>${esc(x.full_name||x.email)}</i>`).join('')||'—'}</div><div class="mini-tags">${gs.map(x=>`<i>${esc(x.name)}</i>`).join('')||'—'}</div><div class="mini-tags">${ls.map(l=>`<i>${l}</i>`).join('')||'—'}</div><button onclick="JULI.openStudent('${s.id}')">Настроить</button></div>`}).join('')}</div>`:'<div class="empty">Ученики не найдены.</div>';updateSelected()}
function updateSelected(){const n=selected.size;$('selectedCount').textContent=n?`Выбрано: ${n}`:'Ничего не выбрано';$('bulkAssignTeacher').disabled=!n;$('bulkAddGroup').disabled=!n}
async function bulkAssignTeacher(){const teacher_id=$('bulkTeacher').value;if(!teacher_id||!selected.size)return;const rows=[...selected].map(student_id=>({teacher_id,student_id,assigned_by:me.id}));const r=await db.from('teacher_student_assignments').upsert(rows,{onConflict:'teacher_id,student_id'});if(r.error){st('Не удалось назначить выбранных учеников.','err');return}st(`✓ Назначено учеников: ${rows.length}.`,'ok');selected.clear();await load()}
async function bulkAddGroup(){const group_id=Number($('bulkGroup').value||0);if(!group_id||!selected.size)return;const rows=[...selected].map(student_id=>({group_id,student_id}));let r=await db.from('student_group_members').upsert(rows,{onConflict:'group_id,student_id'});if(r.error){st('Не удалось добавить учеников в группу.','err');return}const g=S.groups.find(x=>Number(x.id)===group_id);if(g?.teacher_id){r=await db.from('teacher_student_assignments').upsert(rows.map(x=>({teacher_id:g.teacher_id,student_id:x.student_id,assigned_by:me.id})),{onConflict:'teacher_id,student_id'});if(r.error){st('Группа сохранена, но не удалось назначить её Учителю.','err');return}}st(`✓ В группу добавлено учеников: ${rows.length}.`,'ok');selected.clear();await load()}
function openModal(title,body){$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modal').hidden=false;document.body.style.overflow='hidden'}
function closeModal(){if($('modal').hidden)return;$('modal').hidden=true;$('modalBody').innerHTML='';studentEditing=teacherEditing=groupEditing=null;document.body.style.overflow=''}
function openStudent(id){studentEditing=id;const s=byId(id);openModal(s.full_name||s.email,`<div class="modal-section"><h3>Доступ к ступеням</h3><div class="checks">${[1,2,3,4,5,6,7].map(l=>{const a=access(id,l);return `<label class="choice"><input id="ms-${l}" type="checkbox" ${a?.access_granted?'checked':''}><span class="level-title">${l}. ${C[l]}</span><small>${done(id,l)}/6</small></label>`}).join('')}</div></div><div class="modal-section"><h3>Назначенные учителя</h3><div class="checks">${teachers().map(t=>`<label class="choice"><input id="mt-${t.id}" type="checkbox" ${S.ts.some(x=>x.teacher_id===t.id&&x.student_id===id)?'checked':''}><span>${esc(t.full_name||t.email)}</span></label>`).join('')||'<div class="muted">Учителей нет.</div>'}</div></div><div class="modal-section"><h3>Группы</h3><div class="checks">${S.groups.map(g=>`<label class="choice"><input id="mg-${g.id}" type="checkbox" ${S.gm.some(x=>Number(x.group_id)===Number(g.id)&&x.student_id===id)?'checked':''}><span>${esc(g.name)}</span></label>`).join('')||'<div class="muted">Групп нет.</div>'}</div></div><div class="modal-actions"><a class="btn" href="teacher-progress.html?student=${encodeURIComponent(id)}">Прогресс по модулям</a><button class="primary" onclick="JULI.saveStudent()">Сохранить</button></div>`)}
async function saveStudent(){const id=studentEditing;if(!id)return;const oldMap=new Map(S.access.filter(x=>x.student_id===id).map(x=>[Number(x.course_level),x]));const rows=[1,2,3,4,5,6,7].map(l=>{const o=oldMap.get(l)||{};return{student_id:id,course_level:l,access_granted:!!$(`ms-${l}`)?.checked,paid:!!o.paid,paid_at:o.paid_at||null,payment_note:o.payment_note||null}});let r=await db.from('course_access').upsert(rows,{onConflict:'student_id,course_level'});if(r.error){st('Не удалось сохранить ступени.','err');return}const tids=teachers().filter(t=>$(`mt-${t.id}`)?.checked).map(t=>t.id);r=await db.from('teacher_student_assignments').delete().eq('student_id',id);if(r.error){st('Не удалось обновить Учителей.','err');return}if(tids.length){r=await db.from('teacher_student_assignments').insert(tids.map(teacher_id=>({teacher_id,student_id:id,assigned_by:me.id})));if(r.error){st('Не удалось назначить Учителей.','err');return}}const gids=S.groups.filter(g=>$(`mg-${g.id}`)?.checked).map(g=>g.id);r=await db.from('student_group_members').delete().eq('student_id',id);if(r.error){st('Не удалось обновить группы.','err');return}if(gids.length){r=await db.from('student_group_members').insert(gids.map(group_id=>({group_id,student_id:id})));if(r.error){st('Не удалось сохранить группы.','err');return}}closeModal();st('✓ Настройки ученика сохранены.','ok');await load()}
function renderTeachers(){const list=teachers();$('teachers').innerHTML=list.length?`<div class="data-list">${list.map(t=>`<div class="data-row teacher-row"><div><strong>${esc(t.full_name||t.email)}</strong><span>${esc(t.email)}</span></div><span>${teacherStudents(t.id).size} учен.</span><span>${teacherCourses(t.id).size} ступ.</span><div class="row-actions"><button onclick="JULI.openTeacher('${t.id}')">Настроить</button><button class="danger" onclick="JULI.demoteTeacher('${t.id}')">В ученики</button></div></div>`).join('')}</div>`:'<div class="empty">Учителей пока нет.</div>'}
function openTeacherPicker(){const list=[...candidates(),...students()].filter(x=>x.is_active&&!x.archived);openModal('Назначить учителя',`<div class="modal-section"><h3>Поиск пользователя</h3><input id="teacherPickerSearch" class="field" placeholder="Начните вводить имя или email"><div id="teacherPickerResults" class="person-search-results"></div></div>`);const input=$('teacherPickerSearch'),box=$('teacherPickerResults');const render=()=>{const q=input.value.toLowerCase().trim();const rows=list.filter(x=>!q||(x.full_name||'').toLowerCase().includes(q)||(x.email||'').toLowerCase().includes(q)).slice(0,80);box.innerHTML=rows.length?rows.map(x=>`<div class="person-result"><div><strong>${esc(x.full_name||'Без имени')}</strong><span>${esc(x.email)} · ${x.role==='candidate'?'Претендент':'Ученик'}</span></div><button class="primary" onclick="JULI.promoteTeacher('${x.id}')">Назначить учителем</button></div>`).join(''):'<div class="empty">Пользователи не найдены.</div>'};input.oninput=render;render();setTimeout(()=>input.focus(),0)}
async function promoteTeacher(id){const r=await db.from('profiles').update({role:'teacher'}).eq('id',id);if(r.error){st('Не удалось назначить Учителя: '+r.error.message,'err');return}closeModal();st('✓ Пользователь назначен Учителем. Теперь настройте его ступени и учеников.','ok');await load();tab('teachers')}
async function demoteTeacher(id){if(!confirm('Перевести Учителя обратно в Ученики? Его назначения как Учителя будут сняты.'))return;await db.from('teacher_course_assignments').delete().eq('teacher_id',id);await db.from('teacher_student_assignments').delete().eq('teacher_id',id);const r=await db.from('profiles').update({role:'student'}).eq('id',id);if(r.error){st('Не удалось изменить роль.','err');return}st('✓ Пользователь переведён в Ученики.','ok');await load()}
function openTeacher(id){teacherEditing=id;const t=byId(id),assigned=teacherStudents(id),cs=teacherCourses(id);openModal(t.full_name||t.email,`<div class="modal-section"><h3>Ступени Учителя</h3><div class="checks">${[1,2,3,4,5,6,7].map(l=>`<label class="choice"><input id="tc-${l}" type="checkbox" ${cs.has(l)?'checked':''}><span class="level-title">${l}. ${C[l]}</span></label>`).join('')}</div></div><div class="modal-section"><h3>Назначенные ученики</h3><input id="modalSearch" class="field" placeholder="Поиск ученика"><div id="teacherStudentChoices" class="scroll-checks">${students().map(s=>`<label class="choice teacher-student-choice" data-search="${esc(((s.full_name||'')+' '+(s.email||'')).toLowerCase())}"><input id="tu-${s.id}" type="checkbox" ${assigned.has(s.id)?'checked':''}><span>${esc(s.full_name||s.email)}</span></label>`).join('')||'<div class="muted">Учеников нет.</div>'}</div></div><div class="modal-actions"><button class="primary" onclick="JULI.saveTeacher()">Сохранить назначения</button></div>`);$('modalSearch').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.teacher-student-choice').forEach(x=>x.hidden=!x.dataset.search.includes(q))}}
async function saveTeacher(){const id=teacherEditing;if(!id)return;const ls=[1,2,3,4,5,6,7].filter(l=>$(`tc-${l}`)?.checked),ids=students().filter(s=>$(`tu-${s.id}`)?.checked).map(s=>s.id);let r=await db.from('teacher_course_assignments').delete().eq('teacher_id',id);if(r.error){st('Не удалось обновить ступени Учителя.','err');return}if(ls.length){r=await db.from('teacher_course_assignments').insert(ls.map(course_level=>({teacher_id:id,course_level,assigned_by:me.id})));if(r.error){st('Не удалось сохранить ступени Учителя.','err');return}}r=await db.from('teacher_student_assignments').delete().eq('teacher_id',id);if(r.error){st('Не удалось обновить учеников Учителя.','err');return}if(ids.length){r=await db.from('teacher_student_assignments').insert(ids.map(student_id=>({teacher_id:id,student_id,assigned_by:me.id})));if(r.error){st('Не удалось сохранить учеников Учителя.','err');return}}closeModal();st('✓ Назначения Учителя сохранены.','ok');await load()}
function renderGroups(){const list=S.groups;const teacherOptions='<option value="">Без Учителя</option>'+teachers().map(t=>`<option value="${t.id}">${esc(t.full_name||t.email)}</option>`).join('');$('groupTeacher').innerHTML=teacherOptions;$('groups').innerHTML=list.length?list.map(g=>{const count=S.gm.filter(x=>Number(x.group_id)===Number(g.id)).length,t=byId(g.teacher_id);return `<article class="group-card"><div class="group-card-head"><div><h3>${esc(g.name)}</h3><div class="muted">${count} учен. · ${t?esc(t.full_name||t.email):'Учитель не назначен'}${g.start_date?' · '+new Date(g.start_date+'T00:00:00').toLocaleDateString('ru-RU'):''}</div></div><div class="row-actions"><button onclick="JULI.openGroup(${g.id})">Состав</button><button class="danger" onclick="JULI.deleteGroup(${g.id})">Удалить</button></div></div></article>`}).join(''):'<div class="empty">Групп пока нет.</div>'}
async function createGroup(){const name=$('groupName').value.trim();if(!name){st('Введите название группы.','err');return}const r=await db.from('student_groups').insert({name,start_date:$('groupDate').value||null,description:$('groupDesc').value.trim()||null,teacher_id:$('groupTeacher').value||null,created_by:me.id});if(r.error){st('Не удалось создать группу: '+r.error.message,'err');return}$('groupName').value='';$('groupDate').value='';$('groupDesc').value='';st('✓ Группа создана.','ok');await load()}
function openGroup(id){groupEditing=Number(id);const g=S.groups.find(x=>Number(x.id)===Number(id)),members=new Set(S.gm.filter(x=>Number(x.group_id)===Number(id)).map(x=>x.student_id));openModal(g.name,`<div class="modal-section"><h3>Учитель группы</h3><select id="editGroupTeacher" class="select"><option value="">Без Учителя</option>${teachers().map(t=>`<option value="${t.id}" ${g.teacher_id===t.id?'selected':''}>${esc(t.full_name||t.email)}</option>`).join('')}</select></div><div class="modal-section"><h3>Состав группы</h3><input id="groupMemberSearch" class="field" placeholder="Поиск ученика"><div class="scroll-checks">${students().map(s=>`<label class="choice group-member-choice" data-search="${esc(((s.full_name||'')+' '+(s.email||'')).toLowerCase())}"><input id="gu-${s.id}" type="checkbox" ${members.has(s.id)?'checked':''}><span>${esc(s.full_name||s.email)}</span></label>`).join('')}</div></div><div class="modal-actions"><button class="primary" onclick="JULI.saveGroup()">Сохранить группу</button></div>`);$('groupMemberSearch').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.group-member-choice').forEach(x=>x.hidden=!x.dataset.search.includes(q))}}
async function saveGroup(){const id=groupEditing;if(!id)return;const teacher_id=$('editGroupTeacher').value||null,ids=students().filter(s=>$(`gu-${s.id}`)?.checked).map(s=>s.id);let r=await db.from('student_groups').update({teacher_id}).eq('id',id);if(r.error){st('Не удалось сохранить Учителя группы.','err');return}r=await db.from('student_group_members').delete().eq('group_id',id);if(r.error){st('Не удалось обновить состав группы.','err');return}if(ids.length){r=await db.from('student_group_members').insert(ids.map(student_id=>({group_id:id,student_id})));if(r.error){st('Не удалось сохранить состав группы.','err');return}}if(teacher_id&&ids.length){r=await db.from('teacher_student_assignments').upsert(ids.map(student_id=>({teacher_id,student_id,assigned_by:me.id})),{onConflict:'teacher_id,student_id'});if(r.error){st('Группа сохранена, но не удалось назначить учеников Учителю.','err');return}}closeModal();st('✓ Группа сохранена.','ok');await load()}
async function deleteGroup(id){if(!confirm('Удалить группу? Ученики удалены не будут.'))return;const r=await db.from('student_groups').delete().eq('id',id);if(r.error){st('Не удалось удалить группу.','err');return}st('✓ Группа удалена.','ok');await load()}
async function init(){if(!db){location.href='login.html';return}const u=await db.auth.getUser();if(!u.data.user){location.href='login.html';return}const p=await db.from('profiles').select('*').eq('id',u.data.user.id).single();if(p.error||!p.data){location.href='login.html';return}me=p.data;if(me.role!=='superteacher'){location.href=me.role==='teacher'?'teacher.html':me.role==='student'?'student.html':'candidate.html';return}if(!me.is_active||me.archived){await db.auth.signOut();location.href='login.html?blocked=1';return}$('currentUserName').textContent=me.full_name||me.email;try{await load();st('Панель готова.');tab('candidates')}catch(e){console.error(e);st('Не удалось загрузить администрирование.','err')}}
document.addEventListener('click',e=>{const t=e.target.closest('.tab');if(t)tab(t.dataset.tab);const cb=e.target.closest('.sel-student');if(cb){cb.checked?selected.add(cb.dataset.id):selected.delete(cb.dataset.id);updateSelected()}});$('candidateSearch').addEventListener('input',renderCandidates);['studentSearch','studentTeacherFilter','studentGroupFilter'].forEach(id=>$(id).addEventListener(id==='studentSearch'?'input':'change',renderStudents));$('bulkAssignTeacher').addEventListener('click',bulkAssignTeacher);$('bulkAddGroup').addEventListener('click',bulkAddGroup);$('openTeacherPicker').addEventListener('click',openTeacherPicker);$('createGroup').addEventListener('click',createGroup);$('modalClose').addEventListener('click',closeModal);$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('modal').hidden){e.preventDefault();closeModal()}});$('out').addEventListener('click',async()=>{await db.auth.signOut();location.href='./'});
window.JULI={makeStudent,openStudent,saveStudent,openTeacherPicker,promoteTeacher,openTeacher,saveTeacher,demoteTeacher,openGroup,saveGroup,deleteGroup,closeModal};init();
})();