const courseCatalog=window.JULI_COURSE_STRUCTURE||{};
const level=Number(document.body.dataset.courseLevel);
const course=courseCatalog[level];
const configured=window.JULI_SUPABASE_URL&&!window.JULI_SUPABASE_URL.startsWith('YOUR_')&&window.JULI_SUPABASE_ANON_KEY&&!window.JULI_SUPABASE_ANON_KEY.startsWith('YOUR_');
const db=configured&&window.supabase?window.supabase.createClient(window.JULI_SUPABASE_URL,window.JULI_SUPABASE_ANON_KEY):null;
const $=id=>document.getElementById(id);
const app=$('app'),notice=$('notice'),modules=$('modules'),locked=$('locked'),lockedTitle=$('lockedTitle'),lockedText=$('lockedText'),courseTitle=$('courseTitle'),courseSubtitle=$('courseSubtitle'),courseLevel=$('courseLevel'),out=$('out');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let currentProfile=null,completed=new Set();

function blockKind(text){const t=text.trim().toLowerCase();if(t.startsWith('практика')||t.startsWith('задание'))return['Практика','practice'];if(t.startsWith('важно')||t.startsWith('обратите внимание'))return['Важно','important'];if(t.startsWith('цель'))return['Что вы изучите',''];if(t.startsWith('алгоритм')||t.startsWith('последовательность'))return['Алгоритм работы',''];if(t.startsWith('основн')||t.startsWith('ключев'))return['Ключевые моменты',''];return['Теория','']}
function lessonHtml(content){return String(content||'').split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean).map(p=>{const [label,cls]=blockKind(p);return `<div class="lesson-block ${cls}"><strong>${label}</strong><p>${esc(p)}</p></div>`}).join('')}
function contiguousCompleted(){let n=0;while(course&&n<course.modules.length&&completed.has(n+1))n++;return n}
function ensureProgress(){let el=$('courseProgress');if(el)return el;el=document.createElement('section');el.id='courseProgress';el.className='course-progress';notice.insertAdjacentElement('afterend',el);return el}
function renderProgress(){if(currentProfile?.role==='owner')return;const el=ensureProgress();const done=contiguousCompleted(),total=course.modules.length,percent=Math.round(done/total*100),current=Math.min(done+1,total);el.innerHTML=`<div class="course-progress-top"><div><span class="course-progress-kicker">Ваш прогресс</span><strong>${done===total?'Ступень завершена':`Сейчас открыт модуль ${current} из ${total}`}</strong></div><div class="course-progress-value">${percent}%</div></div><div class="course-progress-track"><div class="course-progress-fill" style="width:${percent}%"></div></div><div class="course-progress-steps">${Array.from({length:total},(_,i)=>{const n=i+1,doneStep=n<=done,currentStep=n===current&&done<total;return `<span class="${doneStep?'done':currentStep?'current':''}">${doneStep?'✓':n}</span>`}).join('')}</div><div class="course-progress-note">${done===total?'Все модули подтверждены преподавателем.':`После подтверждения преподавателем модуля ${current} автоматически откроется следующий.`}</div>`}
}
function renderModules(materials){const byModule=new Map();materials.forEach(x=>{if(!byModule.has(x.module_no))byModule.set(x.module_no,[]);byModule.get(x.module_no).push(x)});const owner=currentProfile?.role==='owner',doneCount=contiguousCompleted(),unlockedThrough=owner?course.modules.length:Math.min(doneCount+1,course.modules.length);modules.innerHTML=course.modules.map((def,i)=>{const n=i+1,rows=byModule.get(n)||[],title=rows[0]?.title||def.title,content=rows.map(r=>r.content).filter(Boolean).join('\n\n'),done=!owner&&n<=doneCount,unlocked=owner||n<=unlockedThrough;if(!unlocked)return `<article class="module module-locked" id="module-${n}"><div class="module-lock-icon">🔒</div><div><div class="eyebrow">Модуль ${n}</div><h2>${esc(title)}</h2><div class="module-locked-text">Содержание откроется после подтверждения преподавателем предыдущего модуля.</div></div></article>`;return `<article class="module ${done?'completed':''} ${!owner&&n===unlockedThrough&&doneCount<course.modules.length?'current':''}" id="module-${n}"><div class="eyebrow">Модуль ${n}${done?' · ПРОЙДЕН':''}</div><h2>${esc(title)}</h2>${content?`<div class="lesson">${lessonHtml(content)}</div>`:`<div class="module-empty">Материал модуля пока не опубликован преподавателем.</div>`}<div class="module-footer"><span class="module-state">${owner?'Преподаватель просматривает опубликованный материал':done?'✓ Завершение подтверждено преподавателем':'Текущий модуль · ожидает подтверждения преподавателя'}</span></div></article>`}).join('')}
function scrollToHash(){if(!location.hash)return;const target=document.querySelector(location.hash);if(target&&!target.classList.contains('module-locked'))target.scrollIntoView({behavior:'smooth',block:'start'})}
function lock(title,text){lockedTitle.textContent=title;lockedText.textContent=text;locked.classList.remove('hidden');app.classList.add('hidden')}

async function init(){try{if(!course){lock('Структура курса не загружена','Обновите страницу.');return}document.title=`${course.title} — JULI`;courseTitle.textContent=course.title;courseSubtitle.textContent=course.subtitle;courseLevel.textContent=`Ступень ${level}`;if(!db){lock('Система авторизации не настроена','Не удалось подключить авторизацию.');return}const {data:{user},error:uErr}=await db.auth.getUser();if(uErr||!user){location.href='login.html';return}const {data:profile,error:pErr}=await db.from('profiles').select('*').eq('id',user.id).single();if(pErr||!profile){lock('Профиль не найден','Войдите повторно или обратитесь к преподавателю.');return}currentProfile=profile;if(profile.role!=='owner'&&((Object.hasOwn(profile,'is_active')&&!profile.is_active)||(Object.hasOwn(profile,'archived')&&profile.archived))){await db.auth.signOut();location.href='login.html?blocked=1';return}let allowed=profile.role==='owner';if(!allowed){const {data:access,error:aErr}=await db.from('course_access').select('access_granted').eq('student_id',user.id).eq('course_level',level).maybeSingle();if(aErr){lock('Не удалось проверить доступ','Обновите страницу или обратитесь к преподавателю.');return}allowed=!!access?.access_granted}if(!allowed){lock('Доступ к этой ступени закрыт','Преподаватель ещё не разрешил вам доступ к этому курсу.');return}let progress=[];if(profile.role!=='owner'){const {data,error}=await db.from('student_progress').select('module_no,completed').eq('student_id',user.id).eq('course_level',level);if(error){lock('Не удалось загрузить прогресс','Преподавателю нужно применить актуальную схему Supabase.');return}progress=data||[]}completed=new Set(progress.filter(x=>x.completed).map(x=>Number(x.module_no)));const {data:materials,error:mErr}=await db.from('course_materials').select('module_no,title,content,sort_order').eq('course_level',level).eq('published',true).order('sort_order').order('module_no');if(mErr){console.error('Course materials error:',mErr);lock('Материалы временно недоступны','Не удалось загрузить содержание курса. Проверьте настройки Supabase.');return}locked.classList.add('hidden');app.classList.remove('hidden');notice.textContent=profile.role==='owner'?'Режим преподавателя: просмотр опубликованной версии курса.':'Материалы открываются последовательно. Переход к следующему модулю подтверждает преподаватель.';renderProgress();renderModules(materials||[]);setTimeout(scrollToHash,50)}catch(err){console.error('Course init error:',err);lock('Не удалось открыть курс','Произошла ошибка загрузки. Обновите страницу; если ошибка повторится, обратитесь к преподавателю.')}}

if(out)out.onclick=async()=>{if(db)await db.auth.signOut();location.href='./'};
init();
