(function(){'use strict';
const C=['','Парикмахер с нуля','Женские стрижки','Колористика','Блонд без ошибок','Современные окрашивания','Продвинутый мастер','Колорист-эксперт'];
const db=(window.supabase&&window.JULI_SUPABASE_URL&&window.JULI_SUPABASE_ANON_KEY)?window.supabase.createClient(window.JULI_SUPABASE_URL,window.JULI_SUPABASE_ANON_KEY):null;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
const S={profiles:[],access:[],progress:[],finance:[],tc:[],ts:[]};let me=null;
const students=()=>S.profiles.filter(x=>x.role==='student'&&!x.archived&&x.is_active);const teachers=()=>S.profiles.filter(x=>x.role==='teacher'&&!x.archived&&x.is_active);const byId=id=>S.profiles.find(x=>x.id===id);
const access=(sid,l)=>S.access.find(x=>x.student_id===sid&&Number(x.course_level)===l);const fin=(sid,l)=>S.finance.find(x=>x.student_id===sid&&Number(x.course_level)===l);const done=(sid,l)=>S.progress.filter(x=>x.student_id===sid&&Number(x.course_level)===l&&x.completed).length;
const hasTeacherStudent=(tid,sid)=>S.ts.some(x=>x.teacher_id===tid&&x.student_id===sid);const hasTeacherCourse=(tid,l)=>S.tc.some(x=>x.teacher_id===tid&&Number(x.course_level)===l);
function money(n){return Number(n||0).toLocaleString('ru-RU',{maximumFractionDigits:0})+' ₸'}function st(t,c=''){const e=$('status');e.className='status '+c;e.textContent=t}
async function select(table){const r=await db.from(table).select('*');if(r.error)throw r.error;return r.data||[]}
async function load(){const p=await db.from('profiles').select('*').order('full_name');if(p.error)throw p.error;S.profiles=p.data||[];[S.access,S.progress,S.finance,S.tc,S.ts]=await Promise.all(['course_access','student_progress','course_finance','teacher_course_assignments','teacher_student_assignments'].map(select));fillTeacherFilter();render()}
function fillTeacherFilter(){const old=$('teacherFilter').value;$('teacherFilter').innerHTML='<option value="">Все учителя</option>'+teachers().map(t=>`<option value="${t.id}">${esc(t.full_name||t.email)}</option>`).join('');$('teacherFilter').value=old}
function eligibleTeachers(sid,l){return teachers().filter(t=>hasTeacherStudent(t.id,sid)&&hasTeacherCourse(t.id,l))}
function filteredStudents(){const q=$('search').value.toLowerCase().trim();return students().filter(s=>!q||(s.full_name||'').toLowerCase().includes(q)||(s.email||'').toLowerCase().includes(q))}
function levelsFor(s){const cf=Number($('courseFilter').value||0),tf=$('teacherFilter').value,pf=$('paidFilter').value;return [1,2,3,4,5,6,7].filter(l=>{if(cf&&l!==cf)return false;const f=fin(s.id,l);if(tf&&f?.teacher_id!==tf)return false;if(pf==='paid'&&!f?.paid)return false;if(pf==='unpaid'&&f?.paid)return false;return true})}
function render(){const ss=filteredStudents();let totalPaid=0,totalReward=0,paidCount=0,completedCount=0;S.finance.forEach(f=>{const s=byId(f.student_id);if(!s||s.role!=='student'||s.archived||!s.is_active)return;if(f.paid){paidCount++;totalPaid+=Number(f.payment_amount||0)}if(f.paid&&done(f.student_id,Number(f.course_level))===6){completedCount++;totalReward+=Number(f.payment_amount||0)*Number(f.teacher_reward_percent||0)/100}});$('financeKpis').innerHTML=[['Активных учеников',students().length],['Оплаченных ступеней',paidCount],['Получено',money(totalPaid)],['К начислению',money(totalReward)]].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');const cards=[];for(const s of ss){const levels=levelsFor(s);if(!levels.length)continue;cards.push(`<article class="finance-student"><div class="finance-student-head"><div><h2>${esc(s.full_name||'Без имени')}</h2><span>${esc(s.email)}</span></div><div><span>${levels.length} ступ.</span></div></div>${levels.map(l=>row(s,l)).join('')}</article>`)}$('financeList').innerHTML=cards.length?cards.join(''):'<div class="finance-empty">По выбранным фильтрам финансовых строк нет.</div>'}
function row(s,l){const f=fin(s.id,l)||{},a=access(s.id,l),teachersList=eligibleTeachers(s.id,l),progress=done(s.id,l),amount=Number(f.payment_amount||0),pct=Number(f.teacher_reward_percent||0),reward=amount*pct/100,complete=progress===6;const options='<option value="">Не назначен</option>'+teachersList.map(t=>`<option value="${t.id}" ${f.teacher_id===t.id?'selected':''}>${esc(t.full_name||t.email)}</option>`).join('');return `<div class="finance-course"><div class="course-name"><small>Ступень ${l}</small><strong>${C[l]}</strong><span class="access-mark ${a?.access_granted?'open':''}">${a?.access_granted?'Доступ ученику открыт':'Доступ не открыт'}</span></div><label class="f-label">Учитель<select id="ft-${s.id}-${l}" class="select">${options}</select></label><label class="f-check"><input id="fp-${s.id}-${l}" type="checkbox" ${f.paid?'checked':''}> Оплачено</label><label class="f-label">Сумма<input id="fa-${s.id}-${l}" class="field" type="number" min="0" step="1000" value="${amount}"></label><label class="f-label">Вознаграждение, %<input id="fr-${s.id}-${l}" class="field" type="number" min="0" max="100" step="0.5" value="${pct}"></label><div class="finance-state">Прогресс: <b>${progress}/6</b><br>${complete?`К начислению: <b>${money(reward)}</b>`:'Начисление после завершения 6/6'}</div><button class="primary" onclick="JULI_FINANCE.save('${s.id}',${l})">Сохранить</button></div>`}
async function save(sid,l){const paid=!!$(`fp-${sid}-${l}`)?.checked,amount=Number($(`fa-${sid}-${l}`)?.value||0),pct=Number($(`fr-${sid}-${l}`)?.value||0),teacher_id=$(`ft-${sid}-${l}`)?.value||null,old=fin(sid,l)||{};if(pct<0||pct>100){st('Процент вознаграждения должен быть от 0 до 100.','err');return}const payload={student_id:sid,course_level:l,teacher_id,paid,payment_amount:amount,paid_at:paid?(old.paid_at||new Date().toISOString()):null,teacher_reward_percent:pct,reward_paid:!!old.reward_paid,reward_paid_at:old.reward_paid_at||null,note:old.note||null};const r=await db.from('course_finance').upsert(payload,{onConflict:'student_id,course_level'});if(r.error){st('Не удалось сохранить финансовые данные: '+r.error.message,'err');return}await db.from('course_access').upsert({student_id:sid,course_level:l,access_granted:!!access(sid,l)?.access_granted,paid,paid_at:payload.paid_at,payment_note:`Сумма: ${money(amount)}; вознаграждение учителя: ${pct}%`},{onConflict:'student_id,course_level'});st('✓ Финансовые данные сохранены.','ok');await load()}
async function init(){if(!db){location.href='login.html';return}const u=await db.auth.getUser();if(!u.data.user){location.href='login.html';return}const p=await db.from('profiles').select('*').eq('id',u.data.user.id).single();if(p.error||!p.data){location.href='login.html';return}me=p.data;if(me.role!=='superteacher'){location.href=me.role==='teacher'?'teacher.html':me.role==='student'?'student.html':'candidate.html';return}$('currentUserName').textContent=me.full_name||me.email;try{await load();st('Финансовая панель готова.')}catch(e){console.error(e);st('Не удалось загрузить финансовые данные.','err')}}
['search','courseFilter','teacherFilter','paidFilter'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));$('out').addEventListener('click',async()=>{await db.auth.signOut();location.href='./'});window.JULI_FINANCE={save};init();
})();