(function(){'use strict';
const C=['','Парикмахер с нуля','Женские стрижки','Колористика','Блонд без ошибок','Современные окрашивания','Продвинутый мастер','Колорист-эксперт'];
const db=window.supabase.createClient(window.JULI_SUPABASE_URL,window.JULI_SUPABASE_ANON_KEY),$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const S={profiles:[],access:[],finance:[],progress:[],tc:[],ts:[]};let me=null;const expanded=new Set();
const students=()=>S.profiles.filter(x=>x.role==='student'&&x.is_active&&!x.archived),teachers=()=>S.profiles.filter(x=>x.role==='teacher'&&x.is_active&&!x.archived),byId=id=>S.profiles.find(x=>x.id===id);
const acc=(sid,l)=>S.access.find(x=>x.student_id===sid&&Number(x.course_level)===l),fin=(sid,l)=>S.finance.find(x=>x.student_id===sid&&Number(x.course_level)===l),done=(sid,l)=>S.progress.filter(x=>x.student_id===sid&&Number(x.course_level)===l&&x.completed).length;
const teacherCan=(tid,l)=>S.tc.some(x=>x.teacher_id===tid&&Number(x.course_level)===l);const money=n=>Number(n||0).toLocaleString('ru-RU',{maximumFractionDigits:0})+' ₸';
function st(t,c=''){const e=$('status');e.className='status '+c;e.textContent=t}async function all(t){const r=await db.from(t).select('*');if(r.error)throw r.error;return r.data||[]}
async function load(){const p=await db.from('profiles').select('*').order('full_name');if(p.error)throw p.error;S.profiles=p.data||[];[S.access,S.finance,S.progress,S.tc,S.ts]=await Promise.all(['course_access','course_finance','student_progress','teacher_course_assignments','teacher_student_assignments'].map(all));fillTeachers();render()}
function fillTeachers(){const old=$('teacherFilter').value;$('teacherFilter').innerHTML='<option value="">Все учителя</option>'+teachers().map(t=>`<option value="${t.id}">${esc(t.full_name||t.email)}</option>`).join('');$('teacherFilter').value=old}
function openLevels(sid){return [1,2,3,4,5,6,7].filter(l=>acc(sid,l)?.access_granted)}
function filterStudents(){const q=$('search').value.toLowerCase().trim(),tf=$('teacherFilter').value,sf=$('stateFilter').value;return students().filter(s=>{if(q&&!((s.full_name||'').toLowerCase().includes(q)||(s.email||'').toLowerCase().includes(q)))return false;if(tf&&!S.finance.some(f=>f.student_id===s.id&&f.teacher_id===tf))return false;const ls=openLevels(s.id);if(sf==='no_access'&&ls.length)return false;if(sf==='unpaid'&&!ls.some(l=>!fin(s.id,l)?.paid))return false;if(sf==='active'&&!ls.some(l=>done(s.id,l)>0&&done(s.id,l)<6))return false;if(sf==='complete'&&!ls.some(l=>done(s.id,l)===6))return false;return true})}
function render(){const ss=filterStudents();let paid=0,sum=0,active=0;S.finance.forEach(f=>{const s=byId(f.student_id);if(!s||s.role!=='student'||s.archived||!s.is_active)return;if(f.paid){paid++;sum+=Number(f.payment_amount||0)}});students().forEach(s=>{if(openLevels(s.id).some(l=>done(s.id,l)<6))active++});$('kpis').innerHTML=[['Активных учеников',students().length],['В обучении',active],['Оплачено ступеней',paid],['Получено',money(sum)]].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('students').innerHTML=ss.length?ss.map(card).join(''):'<div class="empty">Ученики по выбранным фильтрам не найдены.</div>';st(`Показано учеников: ${ss.length} из ${students().length}.`)}
function card(s){const open=openLevels(s.id),paid=open.filter(l=>fin(s.id,l)?.paid).length,complete=open.filter(l=>done(s.id,l)===6).length,isOpen=expanded.has(s.id);return `<article class="person"><div class="person-head"><div class="identity"><h2>${esc(s.full_name||'Без имени')}</h2><span>${esc(s.email)}</span></div><div class="summary-tags"><span class="tag">Ступеней: ${open.length}</span><span class="tag">Оплачено: ${paid}</span><span class="tag">Завершено: ${complete}</span></div><button onclick="JULI_STUDENT.toggle('${s.id}')">${isOpen?'Свернуть ▲':'Администрировать ▼'}</button></div>${isOpen?`<div class="person-body">${[1,2,3,4,5,6,7].map(l=>courseRow(s,l)).join('')}</div>`:''}</article>`}
function eligible(l){return teachers().filter(t=>teacherCan(t.id,l))}
function courseRow(s,l){const a=acc(s.id,l)||{},f=fin(s.id,l)||{},d=done(s.id,l),pct=Math.round(d/6*100),amount=Number(f.payment_amount||0),cash=Number(f.teacher_reward_percent||0),reward=amount*cash/100,opts='<option value="">Учитель не назначен</option>'+eligible(l).map(t=>`<option value="${t.id}" ${f.teacher_id===t.id?'selected':''}>${esc(t.full_name||t.email)}</option>`).join('');return `<div class="course-admin"><div class="course-name"><strong><small>СТУПЕНЬ ${l}</small> ${C[l]}</strong><span class="tag">${d===6?'Завершено':d?`Модуль ${Math.min(d+1,6)}`:'Не начато'}</span></div><div class="course-grid"><label>Доступ<input id="a-${s.id}-${l}" type="checkbox" ${a.access_granted?'checked':''}></label><label>Учитель<select id="t-${s.id}-${l}" class="select">${opts}</select></label><label>Оплачено<input id="p-${s.id}-${l}" type="checkbox" ${f.paid?'checked':''}></label><label>Сумма, ₸<input id="m-${s.id}-${l}" class="field" type="number" min="0" step="1000" value="${amount}"></label><label>Кэшбек Учителю, %<input id="c-${s.id}-${l}" class="field" type="number" min="0" max="100" step="0.5" value="${cash}"></label><div class="progressbox">Прогресс<b>${d}/6 · ${pct}%</b><div class="track"><div class="fill" style="width:${pct}%"></div></div>${d===6&&f.paid?`<small>Кэшбек: ${money(reward)}</small>`:''}</div><button class="primary" onclick="JULI_STUDENT.save('${s.id}',${l})">Сохранить</button></div></div>`}
function toggle(id){expanded.has(id)?expanded.delete(id):expanded.add(id);render()}
async function save(sid,l){const access_granted=!!$(`a-${sid}-${l}`).checked,teacher_id=$(`t-${sid}-${l}`).value||null,paid=!!$(`p-${sid}-${l}`).checked,amount=Number($(`m-${sid}-${l}`).value||0),cash=Number($(`c-${sid}-${l}`).value||0);if(cash<0||cash>100){st('Кэшбек должен быть от 0 до 100%.','err');return}const old=fin(sid,l)||{},paid_at=paid?(old.paid_at||new Date().toISOString()):null;let r=await db.from('course_access').upsert({student_id:sid,course_level:l,access_granted,paid,paid_at,payment_note:paid?`Сумма: ${money(amount)}; кэшбек Учителю: ${cash}%`:null},{onConflict:'student_id,course_level'});if(r.error){st('Не удалось сохранить доступ: '+r.error.message,'err');return}r=await db.from('course_finance').upsert({student_id:sid,course_level:l,teacher_id,paid,payment_amount:amount,paid_at,teacher_reward_percent:cash,reward_paid:!!old.reward_paid,reward_paid_at:old.reward_paid_at||null,note:old.note||null},{onConflict:'student_id,course_level'});if(r.error){st('Не удалось сохранить оплату: '+r.error.message,'err');return}if(teacher_id){r=await db.from('teacher_student_assignments').upsert({teacher_id,student_id:sid,assigned_by:me.id},{onConflict:'teacher_id,student_id'});if(r.error){st('Курс сохранён, но не удалось связать Учителя с учеником.','err');return}}st(`✓ ${C[l]}: настройки сохранены.`,'ok');await load();expanded.add(sid);render()}
async function init(){const u=await db.auth.getUser();if(!u.data.user){location.href='login.html';return}const p=await db.from('profiles').select('*').eq('id',u.data.user.id).single();if(p.error||!p.data||p.data.role!=='superteacher'){location.href='login.html';return}me=p.data;$('currentUserName').textContent=me.full_name||me.email;try{await load()}catch(e){console.error(e);st('Не удалось загрузить учеников.','err')}}
['search','teacherFilter','stateFilter'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));$('out').onclick=async()=>{await db.auth.signOut();location.href='./'};window.JULI_STUDENT={toggle,save};init();
})();