(function(){'use strict';
const C=['','Парикмахер с нуля','Женские стрижки','Колористика','Блонд без ошибок','Современные окрашивания','Продвинутый мастер','Колорист-эксперт'];
const db=window.supabase.createClient(window.JULI_SUPABASE_URL,window.JULI_SUPABASE_ANON_KEY),$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const S={profiles:[],tc:[],finance:[],progress:[],access:[]};let me=null;const expanded=new Set();
const teachers=()=>S.profiles.filter(x=>x.role==='teacher'&&x.is_active&&!x.archived),students=()=>S.profiles.filter(x=>x.role==='student'&&x.is_active&&!x.archived),byId=id=>S.profiles.find(x=>x.id===id),done=(sid,l)=>S.progress.filter(x=>x.student_id===sid&&Number(x.course_level)===l&&x.completed).length,money=n=>Number(n||0).toLocaleString('ru-RU',{maximumFractionDigits:0})+' ₸';
const teacherCourses=id=>new Set(S.tc.filter(x=>x.teacher_id===id).map(x=>Number(x.course_level))),teacherFin=id=>S.finance.filter(x=>x.teacher_id===id&&byId(x.student_id)?.role==='student');
function st(t,c=''){const e=$('status');e.className='status '+c;e.textContent=t}async function all(t){const r=await db.from(t).select('*');if(r.error)throw r.error;return r.data||[]}
async function load(){const p=await db.from('profiles').select('*').order('full_name');if(p.error)throw p.error;S.profiles=p.data||[];[S.tc,S.finance,S.progress,S.access]=await Promise.all(['teacher_course_assignments','course_finance','student_progress','course_access'].map(all));render()}
function metrics(t){const fs=teacherFin(t.id),studentIds=new Set(fs.map(f=>f.student_id)),inWork=fs.filter(f=>done(f.student_id,Number(f.course_level))<6&&S.access.some(a=>a.student_id===f.student_id&&Number(a.course_level)===Number(f.course_level)&&a.access_granted)),complete=fs.filter(f=>done(f.student_id,Number(f.course_level))===6),reward=complete.reduce((s,f)=>s+(f.paid?Number(f.payment_amount||0)*Number(f.teacher_reward_percent||0)/100:0),0),paidReward=complete.reduce((s,f)=>s+(f.reward_paid?Number(f.payment_amount||0)*Number(f.teacher_reward_percent||0)/100:0),0);return{students:studentIds.size,inWork:inWork.length,complete:complete.length,reward,pending:Math.max(0,reward-paidReward)}}
function filtered(){const q=$('search').value.toLowerCase().trim(),sf=$('stateFilter').value;return teachers().filter(t=>{if(q&&!((t.full_name||'').toLowerCase().includes(q)||(t.email||'').toLowerCase().includes(q)))return false;const m=metrics(t),cs=teacherCourses(t.id);if(sf==='active'&&!m.inWork)return false;if(sf==='reward'&&!m.pending)return false;if(sf==='no_courses'&&cs.size)return false;return true})}
function render(){const list=filtered();let pending=0,active=0,complete=0;teachers().forEach(t=>{const m=metrics(t);pending+=m.pending;active+=m.inWork;complete+=m.complete});$('kpis').innerHTML=[['Учителей',teachers().length],['Ступеней в работе',active],['Завершено',complete],['Кэшбек к начислению',money(pending)]].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');$('teachers').innerHTML=list.length?list.map(card).join(''):'<div class="empty">Учителя не найдены.</div>';st(`Показано Учителей: ${list.length} из ${teachers().length}.`)}
function card(t){const m=metrics(t),cs=teacherCourses(t.id),open=expanded.has(t.id);return `<article class="person"><div class="person-head"><div class="identity"><h2>${esc(t.full_name||'Без имени')}</h2><span>${esc(t.email)}</span></div><div class="summary-tags"><span class="tag">Ученики: ${m.students}</span><span class="tag">В работе: ${m.inWork}</span><span class="tag">Кэшбек: ${money(m.pending)}</span></div><button onclick="JULI_TEACHERS.toggle('${t.id}')">${open?'Свернуть ▲':'Администрировать ▼'}</button></div>${open?body(t,cs,m):''}</article>`}
function body(t,cs,m){const fs=teacherFin(t.id);return `<div class="person-body"><div class="section-card"><h2>Разрешённые ступени</h2><div class="toolbar">${[1,2,3,4,5,6,7].map(l=>`<label class="tag" style="display:flex;align-items:center;gap:8px"><input id="tc-${t.id}-${l}" type="checkbox" ${cs.has(l)?'checked':''}>${l}. ${C[l]}</label>`).join('')}</div><button class="primary" onclick="JULI_TEACHERS.saveCourses('${t.id}')">Сохранить доступ к ступеням</button></div><div class="section-card"><h2>Преподавание и кэшбек</h2>${fs.length?`<table class="table"><thead><tr><th>Ученик</th><th>Ступень</th><th>Прогресс</th><th>Оплата</th><th>Кэшбек</th><th>Статус</th></tr></thead><tbody>${fs.map(f=>{const s=byId(f.student_id),d=done(f.student_id,Number(f.course_level)),reward=Number(f.payment_amount||0)*Number(f.teacher_reward_percent||0)/100;return `<tr><td>${esc(s?.full_name||s?.email||'—')}</td><td>${f.course_level}. ${C[Number(f.course_level)]}</td><td>${d}/6</td><td>${f.paid?money(f.payment_amount):'Не оплачено'}</td><td>${money(reward)} (${Number(f.teacher_reward_percent||0)}%)</td><td>${d===6?(f.reward_paid?'Выплачен':'К начислению'):'Обучение идёт'}</td></tr>`}).join('')}</tbody></table>`:'<div class="empty">К этому Учителю пока не привязаны оплачиваемые ступени учеников.</div>'}</div></div>`}
function toggle(id){expanded.has(id)?expanded.delete(id):expanded.add(id);render()}
async function saveCourses(tid){const rows=[1,2,3,4,5,6,7].filter(l=>$(`tc-${tid}-${l}`)?.checked).map(course_level=>({teacher_id:tid,course_level,assigned_by:me.id}));let r=await db.from('teacher_course_assignments').delete().eq('teacher_id',tid);if(r.error){st('Не удалось обновить доступ Учителя.','err');return}if(rows.length){r=await db.from('teacher_course_assignments').insert(rows);if(r.error){st('Не удалось сохранить ступени Учителя: '+r.error.message,'err');return}}st('✓ Доступ Учителя к ступеням сохранён.','ok');await load();expanded.add(tid);render()}
async function init(){const u=await db.auth.getUser();if(!u.data.user){location.href='login.html';return}const p=await db.from('profiles').select('*').eq('id',u.data.user.id).single();if(p.error||!p.data||p.data.role!=='superteacher'){location.href='login.html';return}me=p.data;$('currentUserName').textContent=me.full_name||me.email;try{await load()}catch(e){console.error(e);st('Не удалось загрузить Учителей.','err')}}
['search','stateFilter'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',render));$('out').onclick=async()=>{await db.auth.signOut();location.href='./'};window.JULI_TEACHERS={toggle,saveCourses};init();
})();