(function(){'use strict';
const courses=['','Парикмахер с нуля','Женские стрижки','Колористика','Блонд без ошибок','Современные окрашивания','Продвинутый мастер','Колорист-эксперт'];
const configured=window.JULI_SUPABASE_URL&&window.JULI_SUPABASE_ANON_KEY&&window.supabase;
const db=configured?window.supabase.createClient(window.JULI_SUPABASE_URL,window.JULI_SUPABASE_ANON_KEY):null;
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let me=null,students=[],levels=[],access=[],progress=[];
const doneCount=(student,level)=>progress.filter(x=>x.student_id===student&&Number(x.course_level)===Number(level)&&x.completed).length;
const hasAccess=(student,level)=>!!access.find(x=>x.student_id===student&&Number(x.course_level)===Number(level)&&x.access_granted);
function status(text,type=''){const e=$('status');e.className='status '+type;e.textContent=text}
function render(){
 $('teacherName').textContent=me?.full_name||'Учитель';$('courseChips').innerHTML=levels.length?levels.map(l=>`<span class="chip">${l}. ${courses[l]}</span>`).join(''):'<span class="muted">Суперучитель пока не назначил вам ступени.</span>';
 $('students').innerHTML=students.length?students.map(studentCard).join(''):'<div class="empty">Суперучитель пока не назначил вам учеников.</div>';
}
function studentCard(s){return `<article class="card"><div class="card-head"><div><div class="name">${esc(s.full_name||'Ученик')}</div><div class="email">${esc(s.email)}</div></div><span class="badge">Назначен вам</span></div>${levels.map(level=>{const done=doneCount(s.id,level),pct=Math.round(done/6*100);return `<div class="course-row"><div class="course-title"><small>СТУПЕНЬ ${level}</small><strong>${courses[level]}</strong></div><label class="check"><input id="ta-${s.id}-${level}" type="checkbox" ${hasAccess(s.id,level)?'checked':''}> Доступ ученику</label><div class="progress"><div class="line"><span>${done} из 6</span><strong>${pct}%</strong></div><div class="track"><div class="fill" style="width:${pct}%"></div></div></div><a class="btn" href="teacher-progress.html?student=${encodeURIComponent(s.id)}">Модули</a></div>`}).join('')}<div class="actions"><button class="primary" onclick="window.JULI_TEACHER.saveAccess('${s.id}')">Сохранить доступы</button></div></article>`}
async function saveAccess(student){status('Сохраняем доступы...');for(const level of levels){const granted=!!$(`ta-${student}-${level}`)?.checked;const r=await db.rpc('teacher_set_course_access',{p_student_id:student,p_course_level:level,p_access_granted:granted});if(r.error){console.error(r.error);status('Не удалось сохранить доступ. Проверьте назначения и актуальный supabase-schema.sql.','err');return}}status('✓ Доступы ученика сохранены.','ok');await loadData();render()}
async function loadData(){const [tc,ts]=await Promise.all([db.from('teacher_course_assignments').select('course_level').eq('teacher_id',me.id),db.from('teacher_student_assignments').select('student_id').eq('teacher_id',me.id)]);if(tc.error||ts.error)throw tc.error||ts.error;levels=(tc.data||[]).map(x=>Number(x.course_level)).sort((a,b)=>a-b);const ids=(ts.data||[]).map(x=>x.student_id);if(ids.length){const p=await db.from('profiles').select('id,full_name,email,is_active,archived').in('id',ids);if(p.error)throw p.error;students=(p.data||[]).filter(x=>x.is_active&&!x.archived)}else students=[];const [a,pr]=await Promise.all([db.from('course_access').select('student_id,course_level,access_granted'),db.from('student_progress').select('student_id,course_level,module_no,completed')]);if(a.error||pr.error)throw a.error||pr.error;access=a.data||[];progress=pr.data||[]}
async function init(){if(!db){location.href='login.html';return}const u=await db.auth.getUser();if(!u.data.user){location.href='login.html';return}const p=await db.from('profiles').select('*').eq('id',u.data.user.id).single();if(p.error||!p.data){location.href='login.html';return}me=p.data;if(['superteacher','owner'].includes(me.role)){location.href='admin.html';return}if(me.role!=='teacher'){location.href='student.html';return}if(!me.is_active||me.archived){await db.auth.signOut();location.href='login.html?blocked=1';return}try{await loadData();render();status('Показываются только ученики и ступени, назначенные Суперучителем.')}catch(e){console.error(e);status('Не удалось загрузить назначения. Выполните актуальный supabase-schema.sql.','err')}}
$('out').addEventListener('click',async()=>{await db.auth.signOut();location.href='./'});window.JULI_TEACHER={saveAccess};init();
})();