(function(){'use strict';
const courses=['','Парикмахер с нуля','Женские стрижки','Колористика','Блонд без ошибок','Современные окрашивания','Продвинутый мастер','Колорист-эксперт'];
const db=(window.supabase&&window.JULI_SUPABASE_URL&&window.JULI_SUPABASE_ANON_KEY)?window.supabase.createClient(window.JULI_SUPABASE_URL,window.JULI_SUPABASE_ANON_KEY):null;
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let me=null,students=[],levels=[],access=[],progress=[];
function status(text,type=''){const e=$('status');e.className='status '+type;e.textContent=text}
const doneCount=(student,level)=>progress.filter(x=>x.student_id===student&&Number(x.course_level)===Number(level)&&x.completed).length;
function allowedLevels(studentId){const opened=new Set(access.filter(x=>x.student_id===studentId&&x.access_granted).map(x=>Number(x.course_level)));return levels.filter(l=>opened.has(l));}
function stateOf(done){return done===0?'not_started':done>=6?'completed':'in_progress'}
function currentModule(done){return done>=6?'Завершена':`Модуль ${done+1}`}
function filteredRows(){const q=($('studentSearch')?.value||'').toLowerCase().trim(),lf=Number($('levelFilter')?.value||0),sf=$('stateFilter')?.value||'';const rows=[];for(const s of students){for(const level of allowedLevels(s.id)){const done=doneCount(s.id,level);if(q&&!((s.full_name||'').toLowerCase().includes(q)||(s.email||'').toLowerCase().includes(q)))continue;if(lf&&level!==lf)continue;if(sf&&stateOf(done)!==sf)continue;rows.push({s,level,done})}}return rows}
function renderSummary(){const rows=[];for(const s of students)for(const level of allowedLevels(s.id))rows.push({s,level,done:doneCount(s.id,level)});const activeStudents=new Set(rows.map(x=>x.s.id)).size,inProgress=rows.filter(x=>x.done>0&&x.done<6).length,completed=rows.filter(x=>x.done===6).length;$('teacherSummary').innerHTML=[['Назначено учеников',students.length],['В работе сейчас',activeStudents],['Ступеней в процессе',inProgress],['Завершено ступеней',completed]].map(x=>`<div class="summary-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}
function fillLevelFilter(){const el=$('levelFilter'),old=el.value;el.innerHTML='<option value="">Все ступени</option>'+levels.map(l=>`<option value="${l}">${l}. ${esc(courses[l])}</option>`).join('');el.value=old}
function render(){
 $('teacherName').textContent=me?.full_name||'Учитель';if($('currentUserName'))$('currentUserName').textContent=me?.full_name||me?.email||'Учитель';
 $('courseChips').innerHTML=levels.length?levels.map(l=>`<span class="chip">${l}. ${courses[l]}</span>`).join(''):'<span class="muted">Суперучитель пока не назначил вам ступени.</span>';
 fillLevelFilter();renderSummary();const rows=filteredRows();$('resultCount').textContent=`Показано ${rows.length} учебных ступеней у ${new Set(rows.map(x=>x.s.id)).size} учеников`;
 const grouped=new Map();for(const row of rows){if(!grouped.has(row.s.id))grouped.set(row.s.id,{student:row.s,rows:[]});grouped.get(row.s.id).rows.push(row)};
 $('students').innerHTML=grouped.size?[...grouped.values()].map(studentCard).join(''):'<div class="empty">По выбранным фильтрам учеников нет.</div>';
}
function studentCard(group){const s=group.student;return `<article class="card"><div class="card-head"><div><div class="name">${esc(s.full_name||'Ученик')}</div><div class="email">${esc(s.email)}</div></div><span class="badge">${group.rows.length} ступ.</span></div>${group.rows.map(({level,done})=>{const pct=Math.round(done/6*100),state=stateOf(done),stateText=state==='completed'?'Завершено':state==='in_progress'?'В процессе':'Не начато';return `<div class="course-row"><div class="course-title"><small>СТУПЕНЬ ${level}</small><strong>${courses[level]}</strong><span class="current-module">${currentModule(done)} · ${stateText}</span></div><div class="progress"><div class="line"><span>${done} из 6</span><strong>${pct}%</strong></div><div class="track"><div class="fill" style="width:${pct}%"></div></div></div><a class="btn manage-btn" href="teacher-progress.html?student=${encodeURIComponent(s.id)}&level=${level}">${state==='completed'?'Посмотреть':'Открыть прогресс'}</a></div>`}).join('')}</article>`}
async function loadData(){
 const [tc,ts]=await Promise.all([db.from('teacher_course_assignments').select('course_level').eq('teacher_id',me.id),db.from('teacher_student_assignments').select('student_id').eq('teacher_id',me.id)]);if(tc.error||ts.error)throw tc.error||ts.error;
 levels=(tc.data||[]).map(x=>Number(x.course_level)).sort((a,b)=>a-b);const ids=(ts.data||[]).map(x=>x.student_id);
 if(ids.length){const p=await db.from('profiles').select('id,full_name,email,is_active,archived,role').in('id',ids);if(p.error)throw p.error;students=(p.data||[]).filter(x=>x.role==='student'&&x.is_active&&!x.archived).sort((a,b)=>(a.full_name||'').localeCompare(b.full_name||'','ru'))}else students=[];
 const [a,pr]=await Promise.all([db.from('course_access').select('student_id,course_level,access_granted'),db.from('student_progress').select('student_id,course_level,module_no,completed')]);if(a.error||pr.error)throw a.error||pr.error;access=a.data||[];progress=pr.data||[];
}
async function init(){if(!db){location.href='login.html';return}const u=await db.auth.getUser();if(!u.data.user){location.href='login.html';return}const p=await db.from('profiles').select('*').eq('id',u.data.user.id).single();if(p.error||!p.data){location.href='login.html';return}me=p.data;if(me.role==='superteacher'){location.href='admin.html';return}if(me.role==='candidate'){location.href='candidate.html';return}if(me.role!=='teacher'){location.href='student.html';return}if(!me.is_active||me.archived){await db.auth.signOut();location.href='login.html?blocked=1';return}try{await loadData();render();status('Показываются только ученики и ступени, назначенные вам Суперучителем.')}catch(e){console.error(e);status('Не удалось загрузить назначения.','err')}}
['studentSearch','levelFilter','stateFilter'].forEach(id=>$(id)?.addEventListener(id==='studentSearch'?'input':'change',render));$('resetFilters')?.addEventListener('click',()=>{$('studentSearch').value='';$('levelFilter').value='';$('stateFilter').value='';render()});$('out').addEventListener('click',async()=>{await db.auth.signOut();location.href='./'});init();
})();