create table if not exists public.legal_consents (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  consent_version text not null,
  privacy_accepted boolean not null default false,
  terms_accepted boolean not null default false,
  consented_at timestamptz not null default now(),
  source text not null default 'registration'
);

alter table public.legal_consents enable row level security;

revoke all on public.legal_consents from anon;
revoke all on public.legal_consents from authenticated;
grant select on public.legal_consents to authenticated;

create policy "legal consent self read"
on public.legal_consents for select
to authenticated
using ((select auth.uid()) = user_id or (select private.is_superteacher()));

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles(id,email,full_name,role,is_active,archived)
  values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',''),'candidate',true,false)
  on conflict(id) do nothing;

  if coalesce(new.raw_user_meta_data->>'privacy_accepted','false') = 'true'
     and coalesce(new.raw_user_meta_data->>'terms_accepted','false') = 'true' then
    insert into public.legal_consents(user_id, consent_version, privacy_accepted, terms_accepted, consented_at, source)
    values(
      new.id,
      coalesce(nullif(new.raw_user_meta_data->>'consent_version',''),'2026-08-26'),
      true,
      true,
      coalesce((new.raw_user_meta_data->>'consented_at')::timestamptz, now()),
      'registration'
    )
    on conflict(user_id) do nothing;
  end if;

  return new;
end;
$$;
